# -*- coding: utf-8 -*-
"""BMI Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iA5pu3Cfe7FfAFJcQu0HLFdxRKwu8OYz
"""

print("Welcome to the BMI Calculator!")
weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))

bmi = weight / (height * height)

print("Your BMI is:", round(bmi, 2))

if bmi < 18.5:
    print("You are Underweight.")
elif bmi >= 18.5 and bmi < 24.9:
    print("You have Normal weight.")
elif bmi >= 25 and bmi < 29.9:
    print("You are Overweight.")
else:
    print("You are Obese.")